/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_ChungCu.View;

import QL_ChungCu.Model.DAO.ServiceDAO;
import QL_ChungCu.Model.Service;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Huu Tung
 */
public class frmInfoService extends javax.swing.JFrame {

    /**
     * Creates new form frmInfoService
     */
    DefaultTableModel defaultTableModel;
    List<Service> servicelist = new ArrayList<>();
    
    public frmInfoService() {
        initComponents();
        defaultTableModel = (DefaultTableModel) tblInfoService.getModel();
        LoadData();
        this.setLocationRelativeTo(null);
    }
    
    public void LoadData(){
        List<Service> servicelist = ServiceDAO.GetAll();
        
        defaultTableModel.setRowCount(0);
        
        servicelist.forEach(service -> {
            defaultTableModel.addRow( new Object[] {
                defaultTableModel.getRowCount()+1,
                service.getServiceName(),
                service.getPrice(),
                service.getUnit()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfoService = new javax.swing.JTable();
        btnCapNhap = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT DỊCH VỤ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel1.setText("Tên dịch vụ:");

        jLabel2.setText("Đơn giá:");

        jLabel3.setText("Unit:");

        tblInfoService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên dịch vụ", "Đơn giá", "Unit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfoService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInfoServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInfoService);
        if (tblInfoService.getColumnModel().getColumnCount() > 0) {
            tblInfoService.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        btnCapNhap.setText("Cập nhật");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenDV)
                    .addComponent(txtDonGia)
                    .addComponent(txtUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCapNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi)
                    .addComponent(btnCapNhap)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi)
                    .addComponent(btnTimKiem))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtTenDV.setText("");
        txtDonGia.setText("");
        txtUnit.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtTenDV.getText().equals("")){
            sb.append("Tên dịch vụ không được để trống!");
            txtTenDV.setBackground(Color.orange);
        } else {
            txtTenDV.setBackground(Color.white);
        }
        if(txtDonGia.getText().equals("")){
            sb.append("Đơn bạn chưa nhập đơn giá!");
            txtDonGia.setBackground(Color.orange);
        } else {
            txtDonGia.setBackground(Color.white);
        }
        if (txtUnit.getText().equals("")) {
            sb.append("Bạn chưa nhập Unit?");
            txtUnit.setBackground(Color.orange);
        } else{
            txtUnit.setBackground(Color.white);
        }
        if(sb.length()>1){
            JOptionPane.showConfirmDialog(this, sb.toString(), "Lỗi! ", JOptionPane.ERROR_MESSAGE);
        }
        
        String serviceName = txtTenDV.getText();
        int price = Integer.parseInt(txtDonGia.getText());
        String unit = txtUnit.getText();
        
        Service service = new Service(WIDTH, serviceName, price, unit);
        
        ServiceDAO.InsertService(service);
        JOptionPane.showMessageDialog(this, "Dịch vụ đã được lưu!");
        
        LoadData();
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhật dịch vụ?")==JOptionPane.NO_OPTION){
            return;
        }
        int index = tblInfoService.getSelectedRow();
        if(index >= 0 )
        {
            Service service = servicelist.get(index);
            
            int thongbao = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa dịch vụ?");
            System.out.println("thongboa!" + thongbao);
            
            if(thongbao ==0){
            } else {
                ServiceDAO.DeleteService(service.getId());
                LoadData();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên để tìm kiếm ");
        if(input != null && input.length() >0 ) {
            servicelist = ServiceDAO.Search(input);
            
            defaultTableModel.setRowCount(0);
            servicelist.forEach((service) -> {
                defaultTableModel.addRow( new Object[] {
//                    defaultTableModel.getRowCount()+1,
                    service.getServiceName(),
                    service.getPrice(),
                    service.getUnit()
                });
            });
        } else {
            LoadData();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblInfoServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfoServiceMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblInfoService.getSelectedRow();
        
        txtTenDV.setText(tblInfoService.getValueAt(selectedRow, 1).toString());
        txtDonGia.setText(tblInfoService.getValueAt(selectedRow, 2).toString());
        txtUnit.setText(tblInfoService.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_tblInfoServiceMouseClicked

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtTenDV.getText().equals("")){
            sb.append("Tên dịch vụ không được để trống!");
            txtTenDV.setBackground(Color.orange);
        } else {
            txtTenDV.setBackground(Color.white);
        }
        if(txtDonGia.getText().equals("")){
            sb.append("Đơn bạn chưa nhập đơn giá!");
            txtDonGia.setBackground(Color.orange);
        } else {
            txtDonGia.setBackground(Color.white);
        }
        if (txtUnit.getText().equals("")) {
            sb.append("Bạn chưa nhập Unit?");
            txtUnit.setBackground(Color.orange);
        } else{
            txtUnit.setBackground(Color.white);
        }
        if(sb.length()>0){
            JOptionPane.showConfirmDialog(this, sb.toString(), "Lỗi! ", JOptionPane.ERROR_MESSAGE);
        }
        
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn cập nhật dịch vụ?")==JOptionPane.NO_OPTION){
            return;
        }
        
        String serviceName = txtTenDV.getText();
        int price = Integer.parseInt(txtDonGia.getText());
        String unit = txtUnit.getText();
        
        Service service = new Service(WIDTH, serviceName, price, unit);
        
        ServiceDAO.UpdateService(service);
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        
        LoadData();
    }//GEN-LAST:event_btnCapNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInfoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInfoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInfoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInfoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInfoService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfoService;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
